### ISSUE TITLE
Synapse Link for SQL の反映が必要

### ISSUE THREAD

**Issue by nakazax** [gho9o9/SynapseHandsOn#3]
`5. ハンズオン：リアルタイムデータ分析.md` の Synapse Link に関する説明の中で、Synapse Link for SQL は今後対応予定といった記述がある。for SQL Server 2022 および for Azure SQL Database がパブリック プレビューになったことを反映する必要がある。

**Comment by gho9o9** [comment]
@nakazax , ありがとうございます！こんな感じで訂正しました😀
https://github.com/gho9o9/SynapseHandsOn/blob/8ee0d62e01dbd20f11dc348865a19647d56c6bb7/5.%20%E3%83%8F%E3%83%B3%E3%82%BA%E3%82%AA%E3%83%B3%EF%BC%9A%E3%83%AA%E3%82%A2%E3%83%AB%E3%82%BF%E3%82%A4%E3%83%A0%E3%83%87%E3%83%BC%E3%82%BF%E5%88%86%E6%9E%90.md?plain=1#L21
